// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Gst.Audio {

	using System;
	using System.Runtime.InteropServices;

    using GStreamer;

    #region Autogenerated code
	[GLib.GType (typeof (Gst.Audio.AudioDitherMethodGType))]
	public enum AudioDitherMethod {

		None = 0,
		Rpdf = 1,
		Tpdf = 2,
		TpdfHf = 3,
	}

	internal class AudioDitherMethodGType {
		[DllImport (DLL.GstAudio, CallingConvention = CallingConvention.Cdecl)]
		static extern IntPtr gst_audio_dither_method_get_type ();

		public static GLib.GType GType {
			get {
				return new GLib.GType (gst_audio_dither_method_get_type ());
			}
		}
	}
#endregion
}
