// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Gst.Video {

	using System;
	using System.Runtime.InteropServices;

    using GStreamer;

    #region Autogenerated code
	[GLib.GType (typeof (Gst.Video.NavigationQueryTypeGType))]
	public enum NavigationQueryType {

		Invalid = 0,
		Commands = 1,
		Angles = 2,
	}

	internal class NavigationQueryTypeGType {
		[DllImport (DLL.GstVideo, CallingConvention = CallingConvention.Cdecl)]
		static extern IntPtr gst_navigation_query_type_get_type ();

		public static GLib.GType GType {
			get {
				return new GLib.GType (gst_navigation_query_type_get_type ());
			}
		}
	}
#endregion
}
