// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Gst.Video {

	using System;
	using System.Runtime.InteropServices;

    using GStreamer;

    #region Autogenerated code
	[GLib.GType (typeof (Gst.Video.VideoFieldOrderGType))]
	public enum VideoFieldOrder {

		Unknown = 0,
		TopFieldFirst = 1,
		BottomFieldFirst = 2,
	}

	internal class VideoFieldOrderGType {
		[DllImport (DLL.GstVideo, CallingConvention = CallingConvention.Cdecl)]
		static extern IntPtr gst_video_field_order_get_type ();

		public static GLib.GType GType {
			get {
				return new GLib.GType (gst_video_field_order_get_type ());
			}
		}
	}
#endregion
}
