// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Gst.Video {

	using System;
	using System.Runtime.InteropServices;

    using GStreamer;

    #region Autogenerated code
	[GLib.GType (typeof (Gst.Video.VideoGammaModeGType))]
	public enum VideoGammaMode {

		None = 0,
		Remap = 1,
	}

	internal class VideoGammaModeGType {
		[DllImport (DLL.GstVideo, CallingConvention = CallingConvention.Cdecl)]
		static extern IntPtr gst_video_gamma_mode_get_type ();

		public static GLib.GType GType {
			get {
				return new GLib.GType (gst_video_gamma_mode_get_type ());
			}
		}
	}
#endregion
}
