// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Gst.Video {

	using System;
	using System.Runtime.InteropServices;

    using GStreamer;

    #region Autogenerated code
	[GLib.GType (typeof (Gst.Video.VideoVBIParserResultGType))]
	public enum VideoVBIParserResult {

		Done = 0,
		Ok = 1,
		Error = 2,
	}

	internal class VideoVBIParserResultGType {
		[DllImport (DLL.GstVideo, CallingConvention = CallingConvention.Cdecl)]
		static extern IntPtr gst_video_vbi_parser_result_get_type ();

		public static GLib.GType GType {
			get {
				return new GLib.GType (gst_video_vbi_parser_result_get_type ());
			}
		}
	}
#endregion
}
