// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Gst.Video {

	using System;
	using System.Runtime.InteropServices;

    using GStreamer;

    #region Autogenerated code
	[Flags]
	[GLib.GType (typeof (Gst.Video.VideoResamplerFlagsGType))]
	public enum VideoResamplerFlags {

		None = 0,
		HalfTaps = 1,
	}

	internal class VideoResamplerFlagsGType {
		[DllImport (DLL.GstVideo, CallingConvention = CallingConvention.Cdecl)]
		static extern IntPtr gst_video_resampler_flags_get_type ();

		public static GLib.GType GType {
			get {
				return new GLib.GType (gst_video_resampler_flags_get_type ());
			}
		}
	}
#endregion
}
