// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Gst.Video {

	using System;
	using System.Runtime.InteropServices;

    using GStreamer;

    #region Autogenerated code
	[GLib.GType (typeof (Gst.Video.VideoAFDSpecGType))]
	public enum VideoAFDSpec {

		DvbEtsi = 0,
		AtscA53 = 1,
		SmpteSt20161 = 2,
	}

	internal class VideoAFDSpecGType {
		[DllImport (DLL.GstVideo, CallingConvention = CallingConvention.Cdecl)]
		static extern IntPtr gst_video_afd_spec_get_type ();

		public static GLib.GType GType {
			get {
				return new GLib.GType (gst_video_afd_spec_get_type ());
			}
		}
	}
#endregion
}
