// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Gst.Video {

	using System;
	using System.Runtime.InteropServices;

    using GStreamer;

    #region Autogenerated code
	[GLib.GType (typeof (Gst.Video.VideoMatrixModeGType))]
	public enum VideoMatrixMode {

		Full = 0,
		InputOnly = 1,
		OutputOnly = 2,
		None = 3,
	}

	internal class VideoMatrixModeGType {
		[DllImport (DLL.GstVideo, CallingConvention = CallingConvention.Cdecl)]
		static extern IntPtr gst_video_matrix_mode_get_type ();

		public static GLib.GType GType {
			get {
				return new GLib.GType (gst_video_matrix_mode_get_type ());
			}
		}
	}
#endregion
}
