// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Gst.Controller {

	using System;
	using System.Collections;
	using System.Collections.Generic;
	using System.Runtime.InteropServices;

    using GStreamer;

    #region Autogenerated code
	public partial class Global {

		[DllImport(DLL.GstController, CallingConvention = CallingConvention.Cdecl)]
		static extern void gst_timed_value_control_invalidate_cache(IntPtr self);

		public static void TimedValueControlInvalidateCache(Gst.Controller.TimedValueControlSource self) {
			gst_timed_value_control_invalidate_cache(self == null ? IntPtr.Zero : self.Handle);
		}

#endregion
	}
}
