// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace GES
{
    using System;
    using System.Runtime.InteropServices;

    using GStreamer;

    #region Autogenerated code
    [GLib.GType(typeof(GES.EditModeGType))]
    public enum EditMode
    {

        EditNormal = 0,
        Normal = 0,
        EditRipple = 1,
        Ripple = 1,
        EditRoll = 2,
        Roll = 2,
        EditTrim = 3,
        Trim = 3,
        EditSlide = 4,
        Slide = 4,
    }

    internal class EditModeGType
    {
        [DllImport(DLL.GES, CallingConvention = CallingConvention.Cdecl)]
        static extern IntPtr ges_edit_mode_get_type();

        public static GLib.GType GType
        {
            get
            {
                return new GLib.GType(ges_edit_mode_get_type());
            }
        }
    }
    #endregion
}
