// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Gst {

	using System;
	using System.Runtime.InteropServices;

    using GStreamer;

    #region Autogenerated code
	[GLib.GType (typeof (Gst.ClockEntryTypeGType))]
	public enum ClockEntryType {

		Single = 0,
		Periodic = 1,
	}

	internal class ClockEntryTypeGType {
		[DllImport (DLL.GStreamer, CallingConvention = CallingConvention.Cdecl)]
		static extern IntPtr gst_clock_entry_type_get_type ();

		public static GLib.GType GType {
			get {
				return new GLib.GType (gst_clock_entry_type_get_type ());
			}
		}
	}
#endregion
}
