// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Gst {

	using System;
	using System.Runtime.InteropServices;

    using GStreamer;

    #region Autogenerated code
	[GLib.GType (typeof (Gst.DebugColorModeGType))]
	public enum DebugColorMode {

		Off = 0,
		On = 1,
		Unix = 2,
	}

	internal class DebugColorModeGType {
		[DllImport (DLL.GStreamer, CallingConvention = CallingConvention.Cdecl)]
		static extern IntPtr gst_debug_color_mode_get_type ();

		public static GLib.GType GType {
			get {
				return new GLib.GType (gst_debug_color_mode_get_type ());
			}
		}
	}
#endregion
}
