// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Gst {

	using System;
	using System.Runtime.InteropServices;

    using GStreamer;

    #region Autogenerated code
	[GLib.GType (typeof (Gst.IteratorItemGType))]
	public enum IteratorItem {

		Skip = 0,
		Pass = 1,
		End = 2,
	}

	internal class IteratorItemGType {
		[DllImport (DLL.GStreamer, CallingConvention = CallingConvention.Cdecl)]
		static extern IntPtr gst_iterator_item_get_type ();

		public static GLib.GType GType {
			get {
				return new GLib.GType (gst_iterator_item_get_type ());
			}
		}
	}
#endregion
}
