// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Gst {

	using System;
	using System.Runtime.InteropServices;

    using GStreamer;

    #region Autogenerated code
	[Flags]
	[GLib.GType (typeof (Gst.StreamFlagsGType))]
	public enum StreamFlags {

		None = 0,
		Sparse = 1,
		Select = 2,
		Unselect = 4,
	}

	internal class StreamFlagsGType {
		[DllImport (DLL.GStreamer, CallingConvention = CallingConvention.Cdecl)]
		static extern IntPtr gst_stream_flags_get_type ();

		public static GLib.GType GType {
			get {
				return new GLib.GType (gst_stream_flags_get_type ());
			}
		}
	}
#endregion
}
