// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Gst {

	using System;
	using System.Runtime.InteropServices;

    using GStreamer;

    #region Autogenerated code
	[GLib.GType (typeof (Gst.StructureChangeTypeGType))]
	public enum StructureChangeType {

		Link = 0,
		Unlink = 1,
	}

	internal class StructureChangeTypeGType {
		[DllImport (DLL.GStreamer, CallingConvention = CallingConvention.Cdecl)]
		static extern IntPtr gst_structure_change_type_get_type ();

		public static GLib.GType GType {
			get {
				return new GLib.GType (gst_structure_change_type_get_type ());
			}
		}
	}
#endregion
}
