// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Gst {

	using System;
	using System.Runtime.InteropServices;

    using GStreamer;

    #region Autogenerated code
	[GLib.GType (typeof (Gst.TagScopeGType))]
	public enum TagScope {

		Stream = 0,
		Global = 1,
	}

	internal class TagScopeGType {
		[DllImport (DLL.GStreamer, CallingConvention = CallingConvention.Cdecl)]
		static extern IntPtr gst_tag_scope_get_type ();

		public static GLib.GType GType {
			get {
				return new GLib.GType (gst_tag_scope_get_type ());
			}
		}
	}
#endregion
}
