// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Gst.Rtsp {

	using System;
	using System.Runtime.InteropServices;

    using GStreamer;

    #region Autogenerated code
	[GLib.GType (typeof (Gst.Rtsp.RTSPAuthMethodGType))]
	public enum RTSPAuthMethod {

		None = 0,
		Basic = 1,
		Digest = 2,
	}

	internal class RTSPAuthMethodGType {
		[DllImport (DLL.GstRtsp, CallingConvention = CallingConvention.Cdecl)]
		static extern IntPtr gst_rtsp_auth_method_get_type ();

		public static GLib.GType GType {
			get {
				return new GLib.GType (gst_rtsp_auth_method_get_type ());
			}
		}
	}
#endregion
}
