// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Gst.WebRTC {

	using System;
	using System.Runtime.InteropServices;

    using GStreamer;

    #region Autogenerated code
	[GLib.GType (typeof (Gst.WebRTC.WebRTCPeerConnectionStateGType))]
	public enum WebRTCPeerConnectionState {

		New = 0,
		Connecting = 1,
		Connected = 2,
		Disconnected = 3,
		Failed = 4,
		Closed = 5,
	}

	internal class WebRTCPeerConnectionStateGType {
		[DllImport (DLL.GstWebRTC, CallingConvention = CallingConvention.Cdecl)]
		static extern IntPtr gst_webrtc_peer_connection_state_get_type ();

		public static GLib.GType GType {
			get {
				return new GLib.GType (gst_webrtc_peer_connection_state_get_type ());
			}
		}
	}
#endregion
}
