// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Gst.WebRTC {

	using System;
	using System.Runtime.InteropServices;

    using GStreamer;

    #region Autogenerated code
	[GLib.GType (typeof (Gst.WebRTC.WebRTCSCTPTransportStateGType))]
	public enum WebRTCSCTPTransportState {

		New = 0,
		Connecting = 1,
		Connected = 2,
		Closed = 3,
	}

	internal class WebRTCSCTPTransportStateGType {
		[DllImport (DLL.GstWebRTC, CallingConvention = CallingConvention.Cdecl)]
		static extern IntPtr gst_webrtc_sctp_transport_state_get_type ();

		public static GLib.GType GType {
			get {
				return new GLib.GType (gst_webrtc_sctp_transport_state_get_type ());
			}
		}
	}
#endregion
}
