// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Gst.WebRTC {

	using System;
	using System.Runtime.InteropServices;

    using GStreamer;

    #region Autogenerated code
	[GLib.GType (typeof (Gst.WebRTC.WebRTCDataChannelStateGType))]
	public enum WebRTCDataChannelState {

		New = 0,
		Connecting = 1,
		Open = 2,
		Closing = 3,
		Closed = 4,
	}

	internal class WebRTCDataChannelStateGType {
		[DllImport (DLL.GstWebRTC, CallingConvention = CallingConvention.Cdecl)]
		static extern IntPtr gst_webrtc_data_channel_state_get_type ();

		public static GLib.GType GType {
			get {
				return new GLib.GType (gst_webrtc_data_channel_state_get_type ());
			}
		}
	}
#endregion
}
