// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Gst.WebRTC {

	using System;
	using System.Runtime.InteropServices;

    using GStreamer;

    #region Autogenerated code
	[GLib.GType (typeof (Gst.WebRTC.WebRTCDTLSTransportStateGType))]
	public enum WebRTCDTLSTransportState {

		New = 0,
		Closed = 1,
		Failed = 2,
		Connecting = 3,
		Connected = 4,
	}

	internal class WebRTCDTLSTransportStateGType {
		[DllImport (DLL.GstWebRTC, CallingConvention = CallingConvention.Cdecl)]
		static extern IntPtr gst_webrtc_dtls_transport_state_get_type ();

		public static GLib.GType GType {
			get {
				return new GLib.GType (gst_webrtc_dtls_transport_state_get_type ());
			}
		}
	}
#endregion
}
